### PR TITLE
Support for passing/returning Structs by value.

### LINKED ISSUE #3: Support for Passing/Returning Structs by value in Functions
Waiting on support for [Structs by value](https://github.com/dart-lang/sdk/issues/41062) in `dart:ffi`
Currently, functions passing/returning Structs by value are removed from the generated bindings

### PR DESCRIPTION
**Pull request by mannprerak2**
Closes #3 
- Added support for passing/returning structs by value.
- Added, updated tests, examples.
- Updated changelog, readme, version.

### CODE REVIEW

**Comment by mannprerak2** [comment]
@dcharkes Hey, I wanted to know what will happen if we pass a struct (with an incomplete definition by value), but the function was not really expecting that struct?

Currently, I am making sure to not generate any functions which pass/return these incomplete structs by value. Should I be doing this?

**Comment by dcharkes** [comment]
I'm assuming C would give a static error on trying to do something with an incomplete type? If that is the case, then not generating the functions and emitting a warning/error is the right approach.

**Review by dcharkes — COMMENTED** [review]
We should be able to get rid of `lib/src/clang_library/wrapper.c` in this CL right?

**Comment by mannprerak2** [comment]
> We should be able to get rid of lib/src/clang_library/wrapper.c in this CL right?

We can but I think we should do that in another PR.

**Review by dcharkes — APPROVED** [review]
This is a smaller PR than I would have expected. 👍 

lgtm

You might want to make the next PR which removes c wrapper just to dogfood test this PR before we merge it.

**Comment by mannprerak2** [comment]
> I'm assuming C would give a static error on trying to do something with an incomplete type? If that is the case, then not generating the functions and emitting a warning/error is the right approach.

I meant, that sometimes when we remove all struct members if any of the members are unsupported (like bitfield).
So the struct we generate is empty.  So in that case when a user passes this struct by value, how does the dart VM act on this?

**Comment by mannprerak2** [comment]
> You might want to make the next PR which removes C wrapper just to dogfood test this PR before we merge it.

Okay sure

**Comment by dcharkes** [comment]
> > I'm assuming C would give a static error on trying to do something with an incomplete type? If that is the case, then not generating the functions and emitting a warning/error is the right approach.
> 
> I meant, that sometimes when we remove all struct members if any of the members are unsupported (like bitfield).
> So the struct we generate is empty. So in that case when a user passes this struct by value, how does the dart VM act on this?

That would result in segfaults because we would be talking about different registers/stack values. However, empty structs are undefined behavior on C, so `dart:ffi` rejects empty structs in `asFunction` and `fromFunction`. So if you would continue generating, you would generate code that would then be rejected by the Dart compiler.

**Review by dcharkes — APPROVED** [review]

**Pull request merged**
