### PR TITLE
Add include path for systems with LLVM 11 (e.g. Debian 11)

### PR DESCRIPTION
**Pull request by jpnurmi**

### CODE REVIEW

**Review by dcharkes — APPROVED** [review]
lgtm

Thanks @jpnurmi!

**Comment by jpnurmi** [comment]
For some reason, dart_coveralls had failed in the CI. It works for me locally, so perhaps it was just a temporary glitch. I touched the commit message and re-pushed to trigger the CI again.

**Comment by dcharkes** [comment]
I noticed @mannprerak2 updated the file that specifies the coverage in https://github.com/dart-lang/ffigen/pull/122/files#diff-a3b04715795dd54537c7720b57d5afdad3e39f2311232b95b1ec4d43435b5ce9.

@mannprerak2 can we land that separately? Or should we just land that PR, and land this one on top?

**Comment by mannprerak2** [comment]
I think it's best if we can land this PR on top of that.

**Comment by jpnurmi** [comment]
> @jpnurmi can you fix the merge conflicts so that Daco can merge this?

Done!

**Review by dcharkes — APPROVED** [review]

**Pull request merged**
