### PR TITLE
Support nested structs

### LINKED ISSUE #4: Support for Nested Structures
Waiting on support for [Nested Structs](https://github.com/dart-lang/sdk/issues/37271) in `dart:ffi`
Currently, All members of a Struct are removed from bindings if it has another struct as a member

### PR DESCRIPTION
**Pull request by jpnurmi**
Fixes #4

### CODE REVIEW

**Comment by mannprerak2** [comment]
We can also target #3 along with this.

And It is better to put these behind a flag in config for users to enable this, since this will only work on dart master branch as of now.

I think this should be held off until we merge #122 .

**Comment by dcharkes** [comment]
Super cool stuff! 👍 

I second @mannprerak2, we should not merge this into the master branch until nested structs also becomes available in Dart stable. If we merge it into master we can no longer make any changes to `package:ffigen` and release them for Dart stable in the mean time.
(We could make a new branch `dart-master` which we build against the master branch of Dart as you did in this PR in `test-package.yml`. And release a `1.3.0-nested-structs.0` version. However, you can also just use a git dependency to depend on your own branch for the time being. Any preference @jpnurmi ?)

@mannprerak2 do you want to do the reviewing for this PR?

**Comment by jpnurmi** [comment]
Sure, I was planning to get back to this after #122 has been merged. This can be kept in an experimental branch or made configurable as @mannprerak2 suggested. There's no rush from my side to have this upstream, I got the files already generated. :)

**Comment by mannprerak2** [comment]
> @mannprerak2 do you want to do the reviewing for this PR?

Sure.

**Comment by mannprerak2** [comment]
@jpnurmi I think it's best if we create an experimental branch for this (`dart-master` as Daco suggested). Otherwise, we 'dneed to add and then later remove those configs, modify tests to run according to certain configurations. 

Also, we can target #3 as a separate PR, since it needs to know if a struct had been properly generated to be able to pass it by value correctly.

**Comment by mannprerak2** [comment]
@dcharkes I think you would need to create a dart-master branch so that @jpnurmi can make a PR on it.

**Comment by dcharkes** [comment]
Done: https://github.com/dart-lang/ffigen/tree/dart-master

**Pull request closed without merging**
