### PR TITLE
Add `structs` and `enums`'s configurations in the table

### PR DESCRIPTION
**Pull request by Sunbreak**

### CODE REVIEW

**Review by mannprerak2 — COMMENTED** [review]
I don't really see why this was necessary, but I guess there is no harm in doing this.

Can you move the comments to their own previous line? (Similar to other entries in this cell)
That way the 2nd column gets more space.

**Review by mannprerak2 — APPROVED** [review]

**Comment by Sunbreak** [comment]
> I don't really see why this was necessary, but I guess there is no harm adding this.

I was not sure whether `struct`'s `rename` is available because `enum`'s `rename` is not. It took me some time to find the configuration in the FAQ

**Comment by mannprerak2** [comment]
@Sunbreak enum rename is also available.

**Comment by Sunbreak** [comment]
> @Sunbreak enum rename is also available.

I test again and `enum`'s `rename` works. Thanks bro

I'll update the PR with that

**Review by dcharkes — APPROVED** [review]

**Comment by dcharkes** [comment]
Thanks @Sunbreak !

**Pull request merged**
