### PR TITLE
Release Patch 4.1.3

### LINKED ISSUE #265: Analysis error in 4.1.2.
https://pub.dev/packages/ffigen/versions/4.1.2/score

```
$ dart analyze lib/src/header_parser/sub_parsers/compounddecl_parser.dart
Analyzing compounddecl_parser.dart...  2.5s

  error • compounddecl_parser.dart:196:9 • Argument 'exceptionalReturn' must be a constant. Try replacing the value with a literal or const. • argument_must_be_a_constant

1 issue found.
```

We've already fixed this in the 5.0.0 pre-release:
https://pub.dev/packages/ffigen/versions/5.0.0-dev.0/score

We could make a 4.1.3 release to patch this. wdyt @mannprerak2? Worth making a new version for?

They failing analysis could be the cause for [Unidentified] as a label on the package.
image

cc @jonasfj

### PR DESCRIPTION
**Pull request by mannprerak2**
Closes #265.

### CODE REVIEW

**Comment by dcharkes** [comment]
Shouldn't this be a PR to https://github.com/dart-lang/ffigen/tree/stable ?

**Comment by mannprerak2** [comment]
I've changed the base but I'm not sure how to remove the `cla` cehck

**Comment by dcharkes** [comment]
Let's see, can we roll `stable` forward to the last commit on `master` that refers to 4.1.2.

**Comment by mannprerak2** [comment]
Ys, I think we can just move the stable branch upto this commit - `afde222c68b6026e0d5533d630268a12869765b8`. (https://github.com/dart-lang/ffigen/commit/afde222c68b6026e0d5533d630268a12869765b8)

**Comment by mannprerak2** [comment]
Finally managed to remove the CLA error caused by a different git email set on my new machine.

**Comment by mannprerak2** [comment]
Done. Good thing we did that, I had accidentally left a formatting error in there.

**Comment by dcharkes** [comment]
Super!

Can you make a pr to merge fd3e1a7242450eca16ad5824a116036d451967e4 into master? Then we can easily roll forward next time again.

**Pull request merged**
